name: GH Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - run: pnpm install
      - run: pnpm exec turbo --filter=demo build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./demo/dist
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        id: deployment
      - name: Get the URL for the deployment
        run: 'echo "Deployment URL: ${{ steps.deployment.outputs.url }}"'
